server:
  port: 8080
  servlet:
    context-path: /quan-ly-vua-ca


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        # Dòng này quan trọng: Bắt Hibernate dùng đúng tên trong @Column, không tự sửa thành snake_case
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 43200
  refreshable-duration: 604800

vnpay:
  tmn-code: ${TMN_CODE}
  hash-secret: ${HASH_SECRET}
  base-url: ${BASE_URL}
  return-url: ${RETURN_URL}
  version: 2.1.0
  command: pay
  curr-code: VND
  locale: vn

timezone:
  id: Asia/Ho_Chi_Minh

springdoc:
  swagger-ui:
    path: ${SWAGGER_UI}
  api-docs:
    path: ${API_DOCS}

frontend:
  url: ${FRONTEND_URL}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}